### ISSUE TITLE
t test util anomaly

### ISSUE THREAD

**Issue by PhilterPaper** [Perl5-Alien/Alien-Build#193]
Windows 10, Strawberry Perl 5.26.1

I've been seeing this test glitch for a number of releases. In t/alien_build_util.t, it gives: `1/? 'ls' is not recognized as an internal or external command, executable program or batch file`. The command at line 79 is `note <backtick>ls -lR $tmp2<backtick>;` Apparently the Linux emulator used by Strawberry Perl's builder doesn't include an **ls** command. I don't know if you could check the OS and use a **dir** for Windows instead, or if this is something we'll just have to live with. 

The main problem here is that it's possible that not all the subtests are running, and thus testing is incomplete on Windows (or at least, for Strawberry Perl).

**Comment by plicease** [comment]
I think it should be safe to remove these diagnostics.  They were added during testing to eyeball the results, andI believe these are just sent to `note`, which means they are displayed when running the test in verbose mode.  I don't think there is any conditional logic based on the output, but we should either remove or fix these diagnostics so that we get rid of the warnings.
