### ISSUE TITLE
Darwin, Path::Tiny paths require defined positive-length parts

### ISSUE THREAD

**Issue by wbraswell** [Perl5-Alien/Alien-Build#24]
I see this issue on 2 Darwin machines:

http://www.cpantesters.org/cpan/report/6ddf783c-6c99-11e7-bdef-1db1708aea55

Path::Tiny paths require defined, positive-length parts at /Users/hornenj/.cpan/build/Alien-Build-0.66-4/blib/lib/Alien/Build/Util.pm line 107.
make: *** [Makefile:984: _alien/mm/build] Error 255

Also seen here:

http://www.cpantesters.org/cpan/report/55f07862-6c98-11e7-9c0b-198b708aea55

**Comment by plicease** [comment]
May be related to this error:

https://gist.github.com/anonymous/ee27bc1fa0f79d9123dfa3967730c146

I still haven't been able to reproduce this.

**Comment by wbraswell** [comment]
I don't suppose you know Nigel Horne, who owns the Darwin machine(s) in question?
njh@bandsman.co.uk

**Comment by wbraswell** [comment]
@plicease 
Shall I contact Nigel Horne and ask if he can somehow grant you access to his Darwin machine(s)?

**Comment by plicease** [comment]
I was finally able to reproduce this.  Problem is not in OS X, problem was triggered by the use of parallel make (-j).  Have a fix, and has been released as 0.70_01.  0.69_01 had a few failures in cpantesters matrix, but because of CT reliability issues, I am unable to see the logs for those failures.  So it may be a few days before I can resolve those failures and make a production release.

**Comment by plicease** [comment]
(work around for now is to not use -j option on make)

**Comment by wbraswell** [comment]
@plicease 
Okay great, I will wait for your production release, thanks!  :-)
