### ISSUE TITLE
Missing ExtUtils::PkgConfig version-comparison methods

### ISSUE THREAD

**Issue by leonerd** [Perl5-Alien/Alien-Build#75]
An `Alien` module is supposed to provide most of the methods of `ExtUtils::PkgConfig`. I often make use of the `->atleast_version` check to ensure I'm building against a sufficient version of a library. `Alien::Base` does not provide these.

```
$ perl -MAlien::unibilium -E'say Alien::unibilium->atleast_version( "2.0.0" )'
Can't locate object method "atleast_version" via package "Alien::unibilium" at -e line 1.
```

**Comment by leonerd** [comment]
An embedded implementation of them inside the `.pm` file is quite straightforward:

```perl
sub modversion { shift->version }

# Sort::Versions isn't quite the same algorithm because it differs in
# behaviour with leading zeroes.
#   See also  https://dev.gentoo.org/~mgorny/pkg-config-spec.html#version-comparison
sub _versioncmp
{
   my @x = (shift =~ m/(\d+|[a-z]+)/ig);
   my @y = (shift =~ m/(\d+|[a-z]+)/ig);

   while(@x and @y) {
      my $x = shift @x; my $x_isnum = $x =~ m/\d+/;
      my $y = shift @y; my $y_isnum = $y =~ m/\d+/;

      if( $x_isnum and $y_isnum ) {
         # Numerical comparison
         return $x <=> $y if $x != $y;
      }
      elsif( !$x_isnum and !$y_isnum ) {
         # Alphabetic comparison
         return $x cmp $y if $x ne $y;
      }
      else {
         # Of differing types, the numeric one is newer
         return $x_isnum - $y_isnum;
      }
   }

   # Equal so far; the longer is newer
   return @x <=> @y;
}

sub atleast_version
{
   my $self = shift;
   my ( $wantver ) = @_;

   return _versioncmp( $self->modversion, $wantver ) >= 0;
}

sub exact_version
{
   my $self = shift;
   my ( $wantver ) = @_;

   return _versioncmp( $self->modversion, $wantver ) == 0;
}

sub max_version
{
   my $self = shift;
   my ( $wantver ) = @_;

   return _versioncmp( $self->modversion, $wantver ) <= 0;
}
```

I can submit these as a PR if required.

**Comment by plicease** [comment]
I think adding an interface to check the version is good.  I usually check these things in the alienfile or at configure time if it isn't AB based, and if the system lib isn't good enough do a share install and/or skip known bad versions that may come from a share install.

However, I can see the value in this in the case where the XS and Alien authors cannot or will not coordinate, or if one Alien is consumed by a number of modules.  The latter hasn't really happened yet in practice, but the future is difficult to predict.

As for the interface a couple of things I would like to see:

`_versioncmp` should be a public class method (maybe `version_cmp`) so that it can easily be overridden in the subclass.  Although there is a "correct" way to sort pkg-config packages, not all packages use pkg-config or use the pkg-config convention, so it should be as easy as possible to override the comparison function.  I DO think that pkg-config is a good default implementation for the comparison since it is probably the "correct" choice for most common for Perl Aliens, and probably good enough for a lot more as well.

I'm not keen on an alias `modversion` for `version`.  This seems to derive from the `pkg-config` command-line interface.

**Comment by plicease** [comment]
Another thing to consider is aliens where the version cannot be determined.  This happens most often with a system install where the package in question doesn't have a .pc file and doesn't have any version information in the header file.  I think an exception should be thrown in that case.

**Comment by leonerd** [comment]
> `_versioncmp` should be a public class method (maybe `version_cmp`) so that it can easily be overridden in the subclass. Although there is a "correct" way to sort pkg-config packages, not all packages use pkg-config or use the pkg-config convention, so it should be as easy as possible to override the comparison function. I DO think that pkg-config is a good default implementation for the comparison since it is probably the "correct" choice for most common for Perl Aliens, and probably good enough for a lot more as well.

Good thinking, I can do that.

> I'm not keen on an alias `modversion` for `version`. This seems to derive from the `pkg-config` command-line interface, but I don't think that it needs to be duplicated by `Alien::Base`.

It does, I just followed that for completeness. It turns out I don't actually need that particular one so I could remove it.

> Another thing to consider is aliens where the version cannot be determined. This happens most often with a system install where the package in question doesn't have a .pc file and doesn't have any version information in the header file. I think an exception should be thrown in that case.

Seems reasonable.

**Comment by Grinnz** [comment]
Should `\d+` be `[0-9]+` to restrict this to ascii digits?

**Comment by leonerd** [comment]
PR #77

**Comment by leonerd** [comment]
Slightly awkwardly, `pkg-config` doesn't provide a version comparison test that would accept e.g. "1.2.0" or "1.2.99999" as being OK, but "1.3" not OK. For those times when you know you want major.minor 1.2, but any bugfix release of that, but you know that 1.3 would break.

I guess you could simulate it with two calls though;

  $alien->atleast_version( "1.2" ) and not $alien->atleast_version( "1.3" )

**Comment by leonerd** [comment]
#77 is now merged, this seems done.

Thanks :)
